FROM openjdk:17-jdk-alpine

COPY gradlew settings.gradle ./
COPY gradle/ ./gradle/
RUN ./gradlew :wrapper

COPY buildSrc/ ./buildSrc/
RUN ./gradlew :buildSrc:extractPluginRequests
RUN ./gradlew :buildSrc:generatePluginAdapters

COPY microservices/api-gateway/ ./microservices/api-gateway/

RUN ./gradlew :microservices:api-gateway:classes

CMD ["./gradlew", ":microservices:api-gateway:bootRun"]