FROM openjdk:17-jdk-alpine

COPY gradlew settings.gradle ./
COPY gradle/ ./gradle/
RUN ./gradlew :wrapper

COPY buildSrc/ ./buildSrc/
RUN ./gradlew :buildSrc:extractPluginRequests
RUN ./gradlew :buildSrc:generatePluginAdapters

COPY aop-cache-spring-boot-starter/ ./aop-cache-spring-boot-starter/
COPY microservices/comments-service/ ./microservices/comments-service/

RUN ./gradlew :aop-cache-spring-boot-starter:publishToMavenLocal
RUN ./gradlew :microservices:comments-service:classes

CMD ["./gradlew", ":microservices:comments-service:bootRun"]