eureka.client:
  serviceUrl:
    defaultZone: http://eureka:8761/eureka

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sakujj
  datasource:
    url: jdbc:postgresql://postgres_comments:5432/main_db