eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/realms/sakujj
  datasource:
    url: jdbc:postgresql://postgres_news:5432/main_db

spring.data:
  redis:
    host: redis