eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

nms:
  eureka-server:
    uri: http://eureka:8761

spring.security:
  oauth2:
    client:
      provider.keycloak:
#        issuer-uri: http://keycloak:8080/realms/sakujj
        issuer-uri: http://host.docker.internal:8080/realms/sakujj
    resourceserver:
      jwt:
        issuer-uri: http://host.docker.internal:8080/realms/sakujj
